Added Interactive component for manual judgement awaited and callback…
singh09iet/orca pull request #1
Opened 2022-01-24 13:02 UTC by singh09iet

… handler.

We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/docs/community/contributing/code/submitting/#commit-and-pr-message-conventions).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

2022-01-24 15:43 UTC, sanopsmx requested changes
Try to use retrofit Json types rather than jackson json types..Our code should be compatible with the existing retrofit client types.

2022-01-24 15:43 UTC, sanopsmx commented on orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/EchoService.groovy
> +    @JsonTypeInfo(
Try to use retrofit Json types rather than jackson json types..Our code should be compatible with the existing retrofit client types.

2022-01-25 04:08 UTC, singh09iet commented on orca-echo/src/main/groovy/com/netflix/spinnaker/orca/echo/EchoService.groovy
> +    @JsonTypeInfo(
in Echo Service jackson json types got used for same object .

2022-01-27 07:29 UTC, sanopsmx approved these changes

2022-01-27 07:29 UTC, merged